sudo: false

language: node_js

install:
  - npm install

before_script:
  - npm run build
  - ./index.js init

node_js:
  - "6"

notifications:
  email: false
  webhooks: http://cq-dokidokivisual.rhcloud.com/travis

# blacklist
branches:
  except:
    - tmp

cache:
  directories:
    - node_modules
